exports.packets = {
	handshaking: {
		toClient: {},
		toServer: {
			0x00: 'handshake'
		},
	},
	play: {
		toClient: {
			0x00: 'keepAlive',
			0x01: 'joinGame',
			0x02: 'chatMessage',
			0x03: 'timeUpdate',
			0x04: 'entityEquipment',
			0x05: 'spawnPosition',
			0x06: 'updateHealth',
			0x07: 'respawn',
			0x08: 'playerPositionAndLook',
			0x09: 'heldItemChange',
			0x0A: 'useBed',
			0x0B: 'animation',
			0x0C: 'spawnPlayer',
			0x0D: 'collectItem',
			0x0E: 'spawnObject',
			0x0F: 'spawnMob',
			0x10: 'spawnPainting',
			0x11: 'spawnExperienceOrb',
			0x12: 'entityVelocity',
			0x13: 'destroyEntities',
			0x14: 'entity',
			0x15: 'entityRelativeMove',
			0x16: 'entityLook',
			0x17: 'entityLookAndRelativeMove',
			0x18: 'entityTeleport',
			0x19: 'entityHeadLook',
			0x1A: 'entityStatus',
			0x1B: 'attachEntity',
			0x1C: 'entityMetadata',
			0x1D: 'entityEffect',
			0x1E: 'removeEntityEffect',
			0x1F: 'setExperience',
			0x20: 'entityProperties',
			0x21: 'chunkData',
			0x22: 'multiBlockChange',
			0x23: 'blockChange',
			0x24: 'blockAction',
			0x25: 'blockBreakAnimation',
			0x26: 'mapChunkBulk',
			0x27: 'explision',
			0x28: 'effect',
			0x29: 'soundEffect',
			0x2A: 'particle',
			0x2B: 'changeGameState',
			0x2C: 'spawnGlobalEntity',
			0x2D: 'openWindow',
			0x2E: 'closeWindow',
			0x2F: 'setSlot',
			0x30: 'windowItems',
			0x31: 'windowProperty',
			0x32: 'confirmTransaction',
			0x33: 'updateSign',
			0x34: 'maps',
			0x35: 'updateBlockEntity',
			0x36: 'signEditorOpen',
			0x37: 'statistics',
			0x38: 'playerListItem',
			0x39: 'playerAbilities',
			0x3A: 'tabComplete',
			0x3B: 'scoreboardObjective',
			0x3C: 'updateScore',
			0x3D: 'displayScoreboard',
			0x3E: 'teams',
			0x3F: 'pluginMessage',
			0x40: 'disconnect'
		},
		toServer: {
			0x00: 'keepAlive',
			0x01: 'chatMessage',
			0x02: 'useEntity',
			0x03: 'player',
			0x04: 'playerPosition',
			0x05: 'playerLook',
			0x06: 'playerPositionAndLook',
			0x07: 'playerDigging',
			0x08: 'playerBlockPlacement',
			0x09: 'heldItemChange',
			0x0A: 'animation',
			0x0B: 'entityAction',
			0x0C: 'steerVehicle',
			0x0D: 'closeWindow',
			0x0E: 'clickWindow',
			0x0F: 'confirmTransaction',
			0x10: 'creativeInventoryAction',
			0x11: 'enchantItem',
			0x12: 'updateSign',
			0x13: 'playerAbilities',
			0x14: 'tabComplete',
			0x15: 'clientSettings',
			0x16: 'clientStatus',
			0x17: 'pluginMessage'
		}
	},
	status: {
		toClient: {
			0x00: 'response',
			0x01: 'ping',
		},
		toServer: {
			0x00: 'request',
			0x01: 'ping'
		}
	},
	login: {
		toClient: {
			0x00: 'disconnect',
			0x01: 'encryptionRequest',
			0x02: 'loginSuccess'
		},
		toServer: {
			0x00: 'loginStart',
			0x01: 'encryptionResponse'
		}
	}
};
